- name: install monitoring stack
  hosts: all
  remote_user: ubuntu
  become: true
  roles:
  - prometheus
  - grafana
  - ome.cadvisor
- name: install node-exporter
  remote_user: ubuntu
  hosts: all
  become: true
  roles:
  - node-exporter